### ISSUE TITLE
apertium:pron stands for Pronominal Verb not Pronoun

### ISSUE THREAD

**Issue by shash42** [sid-unizar/apertium-lexinfo-mapping#1]
~200-300 entries have errors on eng-spa due to this.

Some parsed examples:
"be"-verb-eng "mostrarse"-pronoun-spa
"have"-verb-eng "accidentarse"-pronoun-spa
"run"-verb-eng "mantenerse"-pronoun-spa
"remain"-verb-eng "mantenerse"-pronoun-spa
"live"-verb-eng "mantenerse"-pronoun-spa

**Comment by jubosgil** [comment]
Thanks for spotting this! Mapping updated with this change.
